# Generated by Django 2.0.5 on 2019-12-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirari', '0034_auto_20190709_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la categoria')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Categoria de producto',
                'abstract': False,
                'default_permissions': [],
                'ordering': ['-id'],
                'verbose_name_plural': 'Categoria de productos',
                'permissions': [('Can_View__CategoryProduct', 'Ve categoria de productos'), ('Can_Create__CategoryProduct', 'Crea categoria de productos'), ('Can_Update__CategoryProduct', 'Modifica categoria de productos'), ('Can_Delete__CategoryProduct', 'Elimina categoria de productos')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del modelo')),
                ('canBySell', models.BooleanField(default=True)),
                ('canByBuy', models.BooleanField(default=True)),
                ('typeProduct', models.CharField(choices=[('Consumible', 'Consumible'), ('Servicio', 'Servicio'), ('Almacenaje', 'Almacenaje')], default='productQuantity', max_length=250, verbose_name='Forma de generar el descuento')),
                ('sellPrice', models.FloatField(blank=True, null=True)),
                ('costPrice', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del producto')),
                ('codebar', models.CharField(max_length=30, verbose_name='Nombre del modelo')),
                ('uid', models.CharField(max_length=30, verbose_name='Nombre del modelo')),
                ('minimumQuantity', models.IntegerField(blank=True, null=True)),
                ('maximumQuantity', models.IntegerField(blank=True, null=True)),
                ('deliveryTerm', models.IntegerField(blank=True, null=True)),
                ('id_bckp', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.CategoryProduct')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Producto',
                'abstract': False,
                'default_permissions': [],
                'ordering': ['-id'],
                'verbose_name_plural': 'Productos',
                'permissions': [('Can_View__Product', 'Ve productos'), ('Can_Create__Product', 'Crea productos'), ('Can_Update__Product', 'Modifica productos'), ('Can_Delete__Product', 'Elimina productos')],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del proveedor')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'abstract': False,
                'default_permissions': [],
                'ordering': ['-id'],
                'verbose_name_plural': 'Proveedores',
                'permissions': [('Can_View__Provider', 'Ve proveedores'), ('Can_Create__Provider', 'Crea proveedores'), ('Can_Update__Provider', 'Modifica proveedores'), ('Can_Delete__Provider', 'Elimina proveedores')],
            },
        ),
    ]
