# Generated by Django 2.0.5 on 2018-11-07 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mirari', '0007_auto_20181025_1307'),
        ('TCS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_service',
            new_name='OrderService',
        ),
    ]
