# Generated by Django 2.0.5 on 2019-12-16 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mirari.STR.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('STR', '0002_auto_20191216_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('historyType', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('ACTUALIZACION', 'ACTUALIZACION')], default='productQuantity', max_length=250, verbose_name='Tipo de producto')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('id_bckp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': [('Can_View__Product', 'Ve productos'), ('Can_Create__Product', 'Crea productos'), ('Can_Update__Product', 'Modifica productos'), ('Can_Delete__Product', 'Elimina productos')],
                'default_permissions': [],
                'abstract': False,
                'verbose_name': 'Producto',
                'ordering': ['-id'],
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=mirari.STR.models.pathProductImage, verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.CategoryProduct', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deliveryDescription',
            field=models.TextField(blank=True, verbose_name='Descripción para pedidos de entrega'),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, verbose_name='NOTAS INTERNAS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='receptionsDescription',
            field=models.TextField(blank=True, verbose_name='Descripción para recepciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Venta $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STR.Product'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
