# Generated by Django 2.0.5 on 2019-12-20 20:55

from django.db import migrations, models
import django.db.models.deletion
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0003_auto_20191216_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(to='STR.Provider', verbose_name='Proveedores'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contactEmail',
            field=models.EmailField(default='example.example.com', help_text='Correo donde llegarán las notificaciones de facturación', max_length=100, verbose_name='Email contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='contactName',
            field=models.CharField(default='Example', help_text='Como identifican tus clientes a tu negocio?', max_length=255, verbose_name='Nombre contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='country',
            field=models.CharField(default='México', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='provider',
            name='curp',
            field=localflavor.mx.models.MXCURPField(blank=True, max_length=18, null=True, verbose_name='C.U.R.P.'),
        ),
        migrations.AddField(
            model_name='provider',
            name='extNumber',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='No. EXT'),
        ),
        migrations.AddField(
            model_name='provider',
            name='intNumber',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='No. INT'),
        ),
        migrations.AddField(
            model_name='provider',
            name='persona',
            field=models.CharField(choices=[('FISICA', 'FISICA'), ('MORAL', 'MORAL')], default='Física', max_length=100, verbose_name='Tipo de persona'),
        ),
        migrations.AddField(
            model_name='provider',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio o Delegación'),
        ),
        migrations.AddField(
            model_name='provider',
            name='razonSocial',
            field=models.CharField(default='Example', help_text='Razón social de persona Física o Moral', max_length=255, verbose_name='Razón social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='provider',
            name='rfc',
            field=localflavor.mx.models.MXRFCField(default='EXAMPLE', max_length=13, verbose_name='RFC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chihuahua', 'Chihuahua'), ('Chiapas', 'Chiapas'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guerrero', 'Guerrero'), ('Guanajuato', 'Guanajuato'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('Sinaloa', 'Sinaloa'), ('San Luis Potosí', 'San Luis Potosí'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='provider',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='provider',
            name='zipcode',
            field=localflavor.mx.models.MXZipCodeField(default=0, max_length=5, verbose_name='CP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='deliveryDescription',
            field=models.TextField(blank=True, verbose_name='Descripción para entregas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximumQuantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad máxima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimumQuantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad mínima'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Alias con el que reconoces este proveedor'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
            preserve_default=False,
        ),
    ]
