# Generated by Django 2.0.5 on 2019-12-20 20:57

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0004_auto_20191220_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contactEmail',
            field=models.EmailField(blank=True, help_text='Correo donde llegarán las notificaciones de facturación', max_length=100, null=True, verbose_name='Email contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contactName',
            field=models.CharField(blank=True, help_text='Quien responde al contacto del negocio?', max_length=255, null=True, verbose_name='Nombre contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='persona',
            field=models.CharField(blank=True, choices=[('FISICA', 'FISICA'), ('MORAL', 'MORAL')], default='Física', max_length=100, null=True, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='razonSocial',
            field=models.CharField(blank=True, help_text='Razón social de persona Física o Moral', max_length=255, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='rfc',
            field=localflavor.mx.models.MXRFCField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zipcode',
            field=localflavor.mx.models.MXZipCodeField(blank=True, max_length=5, null=True, verbose_name='CP'),
        ),
    ]
