# Generated by Django 2.0.5 on 2018-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0004_auto_20181112_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre de la tienda'),
        ),
    ]
