# Generated by Django 2.0.5 on 2020-01-16 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0034_auto_20190709_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('STR', '0006_auto_20191220_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('operationType', models.CharField(choices=[('ORDEN DE ENTREGA', 'ORDEN DE ENTREGA'), ('RECEPCIONES', 'RECEPCIONES')], max_length=250, verbose_name='Tipo de operación')),
                ('status', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('EN ESPERA', 'EN ESPERA'), ('PREPARADO', 'PREPARADO'), ('HECHO', 'HECHO')], default='BORRADOR', max_length=250, verbose_name='Estatus')),
                ('initialDateTime', models.DateTimeField(auto_now_add=True)),
                ('finalDateTime', models.DateTimeField(blank=True, null=True)),
                ('document', models.CharField(blank=True, max_length=250, null=True, verbose_name='Documento de referencia')),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.Provider')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('Can_View__InventoryOrder', 'Ve ordenes de inventario'), ('Can_Create__InventoryOrder', 'Crea ordenes de inventario'), ('Can_Update__InventoryOrder', 'Modifica ordenes de inventario'), ('Can_Delete__InventoryOrder', 'Elimina ordenes de inventario')],
                'abstract': False,
                'default_permissions': [],
                'verbose_name_plural': 'Ordenes de Inventario',
                'verbose_name': 'Orden de Inventario',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('inventoryOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='STR.InventoryOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='STR.Product')),
            ],
            options={
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
                'verbose_name_plural': 'Producto de Orden de Inventario',
                'verbose_name': 'Producto de Orden de Inventario',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='name',
            field=models.CharField(help_text='Nombre con el que identificas al almacén', max_length=250, verbose_name='Alias'),
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
