# Generated by Django 2.0.5 on 2020-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0007_auto_20200116_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='operationType',
            field=models.CharField(choices=[('ORDEN DE ENTREGA', 'ORDEN DE ENTREGA'), ('RECEPCION', 'RECEPCION')], max_length=250, verbose_name='Tipo de operación'),
        ),
    ]
