# Generated by Django 2.0.5 on 2020-01-27 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0008_auto_20200121_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='STR.Product'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.Provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
