# Generated by Django 2.0.5 on 2019-01-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0009_auto_20190104_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='serial',
        ),
    ]
