# Generated by Django 2.0.5 on 2020-01-28 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0010_auto_20200127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codebar',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, null=True, to='STR.Provider', verbose_name='Proveedores'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia interna (PKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
