# Generated by Django 2.0.5 on 2020-02-11 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0011_auto_20200128_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderproduct',
            name='inventoryOrder',
        ),
        migrations.RemoveField(
            model_name='inventoryorderproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, to='STR.Provider', verbose_name='Proveedores'),
        ),
        migrations.AlterField(
            model_name='product',
            name='typeProduct',
            field=models.CharField(choices=[('Consumible', 'Consumible'), ('Servicio', 'Servicio'), ('Almacenaje', 'Almacenaje')], default='Almacenaje', max_length=250, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
        migrations.DeleteModel(
            name='InventoryOrderProduct',
        ),
    ]
