# Generated by Django 2.0.5 on 2020-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0013_auto_20200221_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
