# Generated by Django 2.0.5 on 2020-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0014_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PKU'),
        ),
    ]
