# Generated by Django 2.0.5 on 2020-03-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0015_auto_20200226_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ubicación'),
        ),
    ]
