# Generated by Django 2.0.5 on 2020-04-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0017_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='CANTIDAD ACTUAL'),
        ),
    ]
