# Generated by Django 2.0.5 on 2020-04-16 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0018_auto_20200413_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrderProoduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [],
                'default_permissions': [],
                'verbose_name': 'Producto de Orden de Inventario',
                'abstract': False,
                'verbose_name_plural': 'Productos de Orden de Inventario',
            },
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='operationType',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=250, verbose_name='Tipo de operación'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.Product'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.Provider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventoryorderprooduct',
            name='inventoryorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='STR.InventoryOrder'),
        ),
        migrations.AddField(
            model_name='inventoryorderprooduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='STR.Product'),
        ),
    ]
