# Generated by Django 2.0.5 on 2020-04-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0019_auto_20200415_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='status',
            field=models.CharField(choices=[('EN ESPERA', 'EN ESPERA'), ('PREPARADO', 'PREPARADO'), ('HECHO', 'HECHO')], default='EN ESPERA', max_length=250, verbose_name='Estatus'),
        ),
    ]
