# Generated by Django 2.0.5 on 2019-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0020_modelo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de la orden'),
        ),
    ]
