# Generated by Django 2.0.5 on 2019-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0022_auto_20190227_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='contact_phone3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Teléfono movil'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='contact_phone1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Teléfono casa'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Teléfono oficina'),
        ),
    ]
