# Generated by Django 2.0.5 on 2019-02-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0025_orderservice_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='serial',
        ),
    ]
