# Generated by Django 2.0.5 on 2019-02-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0026_remove_profile_y'),
        ('TCS', '0029_auto_20190228_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
    ]
