# Generated by Django 2.0.5 on 2019-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0036_auto_20190704_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservice',
            options={'default_permissions': [], 'ordering': ['-serial'], 'permissions': [('Can_View__OrderService', 'Ve ordenes de servicio'), ('Can_Create__OrderService', 'Crea ordenes de servicio'), ('Can_Update__OrderService', 'Modifica ordenes de servicio')], 'verbose_name': 'Orden de servicio', 'verbose_name_plural': 'Ordenes de servicio'},
        ),
    ]
