# Generated by Django 2.0.5 on 2019-07-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0042_auto_20190726_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Modelo', 'Ve modelos'), ('Can_Create__Modelo', 'Crea modelos'), ('Can_Update__Modelo', 'Modifica modelos'), ('Can_Delete__Modelo', 'Elimina modelos')], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
    ]
