# Generated by Django 2.0.5 on 2019-07-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0043_auto_20190726_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre de la marca'),
        ),
        migrations.AlterField(
            model_name='store',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TCS.Company', verbose_name='Empresa'),
        ),
    ]
