# Generated by Django 2.0.5 on 2019-08-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0044_auto_20190727_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'ordering': ['-id_bckp'], 'permissions': [('Can_View__Store', 'Ve tiendas'), ('Can_Create__Store', 'Crea tiendas'), ('Can_Update__Store', 'Modifica tiendas'), ('Can_Delete__Store', 'Elimina tiendas')], 'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.CharField(choices=[('Icon', 'Icon'), ('Tecnoservicio', 'Tecnoservicio'), ('MexicoF', 'MexicoF'), ('eComerce', 'eComerce')], default='Icon', max_length=250, verbose_name='Tipo de servicio'),
        ),
    ]
