# Generated by Django 2.0.5 on 2019-08-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0048_auto_20190807_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservicecomment',
            options={'default_permissions': [], 'ordering': ['-creation_date'], 'permissions': [('Can_View__OrderServiceComment', 'Ve comentarios de orden'), ('Can_Create__OrderServiceComment', 'Crea comentarios de orden'), ('Can_Update__OrderServiceComment', 'Modifica comentarios de orden'), ('Can_Delete__OrderServiceComment', 'Elimina comentarios de orden')], 'verbose_name': 'Comentario de Orden', 'verbose_name_plural': 'Comentarios de Orden'},
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.CharField(choices=[('Icon', 'Icon'), ('Tecnoservicio', 'Tecnoservicio'), ('MexicoF', 'MexicoF'), ('eComerce', 'eCommerce'), ('Yeekang', 'Yeekang'), ('MadeTrader', 'MadeTrader')], default='Icon', max_length=250, verbose_name='Tipo de servicio'),
        ),
    ]
