# Generated by Django 2.0.5 on 2018-09-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsservicessat',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='division',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='ieps_transladado',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='iva_transladado',
        ),
        migrations.RemoveField(
            model_name='productsservicessat',
            name='tipo',
        ),
    ]
