# Generated by Django 2.0.5 on 2018-10-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0003_auto_20181002_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('db_name', models.CharField(blank=True, max_length=250, null=True)),
                ('db_host', models.CharField(blank=True, max_length=250, null=True)),
                ('db_user', models.CharField(blank=True, max_length=250, null=True)),
                ('db_password', models.CharField(blank=True, max_length=250, null=True)),
                ('db_datatable', models.CharField(blank=True, max_length=250, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'DBConnection',
                'verbose_name_plural': 'DBConnection',
                'ordering': ['-id'],
                'permissions': [('Can_View__DBConnection', 'Ve dbconnection'), ('Can_Create__DBConnection', 'Crea dbconnection'), ('Can_Update__DBConnection', 'Modifica dbconnection'), ('Can_Delete__DBConnection', 'Elimina dbconnection')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
