# Generated by Django 2.0.5 on 2018-10-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0004_dbconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('app', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('port', models.CharField(default='', max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('prefix', models.CharField(max_length=250)),
                ('is_available', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'HostEmail',
                'verbose_name_plural': 'HostEmail',
                'ordering': ['-id'],
                'permissions': [('Can_View__HostEmail', 'Ve hostemail'), ('Can_Create__HostEmail', 'Crea hostemail'), ('Can_Update__HostEmail', 'Modifica hostemail'), ('Can_Delete__HostEmail', 'Elimina hostemail')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
