# Generated by Django 2.0.5 on 2018-10-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0006_auto_20181009_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'DBConnection', 'verbose_name_plural': 'DBConnection'},
        ),
        migrations.AlterModelOptions(
            name='hostemail',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'HostEmail', 'verbose_name_plural': 'HostEmail'},
        ),
        migrations.AlterModelOptions(
            name='productsservicessat',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Producto o Servicio', 'verbose_name_plural': 'Productos o servicios'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='unitscodessat',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Clave Unidad', 'verbose_name_plural': 'Clave de Unidades'},
        ),
    ]
