# Generated by Django 2.0.5 on 2018-11-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mirari', '0007_auto_20181025_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('folder', models.CharField(max_length=250)),
                ('ManyToManyField', models.CharField(max_length=250)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'abstract': False,
                'default_permissions': [],
                'permissions': [],
                'verbose_name_plural': 'HostEmail',
                'ordering': ['-id'],
                'verbose_name': 'HostEmail',
            },
        ),
    ]
