# Generated by Django 2.0.5 on 2018-11-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0008_htmlpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlpage',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'PaginasHTML', 'verbose_name_plural': 'PaginasHTML'},
        ),
    ]
