# Generated by Django 2.0.5 on 2018-11-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0009_auto_20181113_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlpage',
            old_name='ManyToManyField',
            new_name='index',
        ),
        migrations.RemoveField(
            model_name='htmlpage',
            name='sites',
        ),
    ]
