# Generated by Django 2.0.5 on 2018-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0010_auto_20181113_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='static',
            field=models.CharField(default='pages/credipyme/static/', max_length=250),
            preserve_default=False,
        ),
    ]
