# Generated by Django 2.0.5 on 2018-11-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0011_htmlpage_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
