# Generated by Django 2.0.5 on 2018-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0013_auto_20181207_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='INDEX_TEMPLATE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
