# Generated by Django 2.0.5 on 2018-12-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0014_organization_index_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='INDEX_TEMPLATE',
        ),
    ]
