# Generated by Django 2.0.5 on 2018-12-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0015_remove_organization_index_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='FACEBOOK',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='REGISTER',
        ),
    ]
