# Generated by Django 2.0.5 on 2019-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0016_auto_20181219_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='DASHBOARD_LOGO_WIDTH',
            field=models.PositiveIntegerField(blank=True, default='0', help_text='px', null=True),
        ),
    ]
