# Generated by Django 2.0.5 on 2019-02-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0017_organization_dashboard_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_bckp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
