# Generated by Django 2.0.5 on 2019-02-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0018_user_id_bckp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_bckp',
            new_name='bckp',
        ),
    ]
