# Generated by Django 2.0.5 on 2019-02-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0019_auto_20190226_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bckp',
            new_name='id_bckp',
        ),
    ]
