# Generated by Django 2.0.5 on 2019-02-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0020_auto_20190226_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible_name2',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
