# Generated by Django 2.0.5 on 2019-02-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0020_auto_20190226_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible_name',
            field=models.CharField(default='Por definir', max_length=100, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
