# Generated by Django 2.0.5 on 2019-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0021_profile_visible_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visible_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del perfil'),
        ),
    ]
