# Generated by Django 2.0.5 on 2019-02-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0021_profile_visible_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visible_name2',
        ),
    ]
