# Generated by Django 2.0.5 on 2019-02-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0023_user_can_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='is_visible',
        ),
    ]
