# Generated by Django 2.0.5 on 2019-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0024_auto_20190228_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='y',
            field=models.CharField(default='Sin asignar', max_length=150, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
