# Generated by Django 2.0.5 on 2019-02-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0025_profile_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='y',
        ),
    ]
