# Generated by Django 2.0.5 on 2019-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0026_remove_profile_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
