# Generated by Django 2.0.5 on 2019-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0027_auto_20190319_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ticketInvoiceLoginButton',
            field=models.BooleanField(default=False, verbose_name='Botón de facturacón en el login'),
        ),
    ]
