# Generated by Django 2.0.5 on 2019-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0028_organization_ticketinvoiceloginbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ticketInvoiceLoginButton',
            field=models.BooleanField(default=False, verbose_name='Botón de facturacón de tickets en el login'),
        ),
    ]
