# Generated by Django 2.0.5 on 2019-06-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0029_auto_20190626_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostemail',
            old_name='company',
            new_name='organization',
        ),
    ]
