# Generated by Django 2.0.5 on 2019-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0030_auto_20190627_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(default='#191919', max_length=50, verbose_name='Color de la empresa'),
        ),
    ]
