# Generated by Django 2.0.5 on 2019-07-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0031_organization_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needChangePassword',
            field=models.BooleanField(default=False, help_text='El usuario debe cambiar su contraseña al primer inicio de sesión?', verbose_name='Debe cambiar la contraseña?'),
        ),
    ]
