# Generated by Django 2.0.5 on 2019-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0033_auto_20190709_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='mail@mirari.xyz', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
