# Generated by Django 2.0.5 on 2018-12-19 18:51

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mirari.mirari.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirari', '0014_organization_index_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('file', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Menor a 12mb', null=True, upload_to=mirari.mirari.models.path_system)),
                ('description', models.CharField(max_length=250, verbose_name='Descripción de la foto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'FOTO',
                'verbose_name_plural': 'FOTOS',
                'ordering': ['-id'],
                'permissions': [('Can_View__Photo', 'Ve fotos'), ('Can_Create__Photo', 'Crea fotos'), ('Can_Update__Photo', 'Modifica fotos'), ('Can_Delete__Photo', 'Elimina fotos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
