# Generated by Django 2.0.5 on 2018-12-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHOTO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
