# Generated by Django 2.0.5 on 2018-12-19 19:04

from django.db import migrations
import imagekit.models.fields
import mirari.mirari.models


class Migration(migrations.Migration):

    dependencies = [
        ('PHOTO', '0002_photo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Menor a 12mb', null=True, upload_to=mirari.mirari.models.path_system, verbose_name='Fotografía'),
        ),
    ]
