# Generated by Django 2.0.5 on 2018-12-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHOTO', '0003_auto_20181219_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Photo', 'Ve fotos'), ('Can_Create__Photo', 'Crea fotos'), ('Can_Update__Photo', 'Modifica fotos'), ('Can_Delete__Photo', 'Elimina fotos')], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
