# Generated by Django 2.0.5 on 2018-12-19 21:23

from django.db import migrations
import imagekit.models.fields
import mirari.PHOTO.models


class Migration(migrations.Migration):

    dependencies = [
        ('PHOTO', '0004_auto_20181219_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Menor a 12mb', null=True, upload_to=mirari.PHOTO.models.path_photo_file, verbose_name='Fotografía'),
        ),
    ]
