# Generated by Django 2.0.5 on 2019-01-24 23:58

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0016_auto_20181219_1659'),
        ('PHOTO', '0006_auto_20190124_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la categoria')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['-id'],
                'permissions': [('Can_View__Category', 'Ve categorías'), ('Can_Create__Category', 'Crea categorías'), ('Can_Update__Category', 'Modifica categorías'), ('Can_Delete__Category', 'Elimina categorías')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(to='PHOTO.Category'),
        ),
    ]
