# Generated by Django 2.0.5 on 2019-01-25 00:32

from django.db import migrations, models
import imagekit.models.fields
import mirari.PHOTO.models


class Migration(migrations.Migration):

    dependencies = [
        ('PHOTO', '0007_auto_20190124_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publica',
            field=models.BooleanField(default=False, help_text='Indica si tu imagen tendra una marca de agua que evite que la roben.'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(to='PHOTO.Category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(help_text='Menos de 250 caracteres', max_length=250, verbose_name='Descripción de la foto'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Menor a 12mb', null=True, upload_to=mirari.PHOTO.models.path_photo_file, verbose_name='Imagen'),
        ),
    ]
