# Generated by Django 2.0.5 on 2019-06-10 00:03

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0002_auto_20190608_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalmx',
            name='contactEmail',
            field=models.EmailField(default='email@email.com', help_text='Correo donde llegarán las notificaciones sobre facturación', max_length=100, verbose_name='Email contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalmx',
            name='persona',
            field=models.CharField(choices=[('FISICA', 'FISICA'), ('MORAL', 'MORAL')], default='Física', max_length=100, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='fiscalmx',
            name='razon_social',
            field=models.CharField(default='Razon Social', help_text='Razón social de persona Física o Moral', max_length=255, verbose_name='Razón social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalmx',
            name='rfc',
            field=localflavor.mx.models.MXRFCField(default='SUL010720JN8', max_length=13, verbose_name='RFC'),
            preserve_default=False,
        ),
    ]
