# Generated by Django 2.0.5 on 2019-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0004_auto_20190611_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='CfdiReceptorNombre',
            new_name='cfdiReceptorNombre',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='CfdiReceptorRegimenFiscal',
            new_name='cfdiReceptorRegimenFiscal',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='CfdiReceptorRfc',
            new_name='cfdiReceptorRfc',
        ),
        migrations.AddField(
            model_name='invoice',
            name='incidencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
