# Generated by Django 2.0.5 on 2019-06-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0005_auto_20190614_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cfdiReceptorRegimenFiscal',
            new_name='cfdiReceptorUsocfdi',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tipoCambio',
        ),
    ]
