# Generated by Django 2.0.5 on 2019-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0006_auto_20190614_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='noCertificadoSAT',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
