# Generated by Django 2.0.5 on 2019-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0007_invoice_nocertificadosat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='noCertificadoSAT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
