# Generated by Django 2.0.5 on 2019-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0008_auto_20190614_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sello',
            field=models.TextField(blank=True, null=True),
        ),
    ]
