# Generated by Django 2.0.5 on 2019-06-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0027_auto_20190319_1636'),
        ('INV', '0009_auto_20190614_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalmx',
            name='serial',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios en 0 o manualmente </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios'),
        ),
    ]
