# Generated by Django 2.0.5 on 2019-06-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0010_fiscalmx_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalmx',
            name='serial',
        ),
    ]
