# Generated by Django 2.0.5 on 2019-06-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0011_remove_fiscalmx_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalmx',
            name='phone',
        ),
    ]
