# Generated by Django 2.0.5 on 2019-06-26 21:10

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0012_remove_fiscalmx_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalmx',
            name='contactEmail',
            field=models.EmailField(help_text='Correo donde llegarán las notificaciones de facturación', max_length=100, verbose_name='Email contacto'),
        ),
        migrations.AlterField(
            model_name='fiscalmx',
            name='contactName',
            field=models.CharField(default='Mirari', help_text='Como identifican tus clientes a tu negocio?', max_length=255, verbose_name='Nombre contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalmx',
            name='zipcode',
            field=localflavor.mx.models.MXZipCodeField(default='15800', max_length=5, verbose_name='CP.'),
            preserve_default=False,
        ),
    ]
