# Generated by Django 2.0.5 on 2019-02-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_group_visible_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='visible_name',
        ),
    ]
