# Generated by Django 2.0.5 on 2019-02-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_remove_group_visible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visible_name',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
