# Generated by Django 2.0.5 on 2019-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_group_visible_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visible_name',
            field=models.CharField(max_length=150, verbose_name='Nombre del perfil'),
        ),
    ]
