# Generated by Django 2.0.5 on 2019-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20190227_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visible_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del perfil'),
        ),
    ]
