# Generated by Django 2.0.5 on 2019-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_auto_20190228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visible_name',
            field=models.CharField(default='Sin Asignar', max_length=150, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
