# Generated by Django 2.0.5 on 2019-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_auto_20190228_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='visible_name',
        ),
        migrations.AddField(
            model_name='group',
            name='v',
            field=models.CharField(default='Sin Asignar', max_length=150, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
