# Generated by Django 2.0.5 on 2019-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_auto_20190228_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='v',
        ),
        migrations.AddField(
            model_name='group',
            name='visible_name',
            field=models.CharField(default='Sin asignar', max_length=150, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
    ]
