# Generated by Django 2.0.5 on 2018-09-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirari', '0002_auto_20180918_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código del documento')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre del documento')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['-id'],
                'permissions': [('Can_View__Catalogue', 'Ve catálogos'), ('Can_Create__Catalogue', 'Crea catálogos'), ('Can_Update__Catalogue', 'Modifica catálogos'), ('Can_Delete__Catalogue', 'Elimina catálogos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
