# Generated by Django 2.0.5 on 2018-09-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0002_auto_20180918_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('INT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('members', models.ManyToManyField(blank=True, related_name='_team_members_+', to=settings.AUTH_USER_MODEL, verbose_name='Miembros de equipo')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-id'],
                'permissions': [('Can_View__Team', 'Ve equipos'), ('Can_Create__Team', 'Crea equipos'), ('Can_Update__Team', 'Modifica equipos'), ('Can_Delete__Team', 'Elimina equipos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
