# Generated by Django 2.0.5 on 2018-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0003_handbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
