# Generated by Django 2.0.5 on 2018-09-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mirari.INT.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mirari', '0002_auto_20180918_1515'),
        ('INT', '0005_chanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500, verbose_name='Notas')),
                ('files', models.FileField(blank=True, null=True, upload_to=mirari.INT.models.path_Notification_file, verbose_name='Archivo adjunto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('deleted', 'Borrado')], default='draft', max_length=250)),
                ('datetime_expire', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
                ('readed_by', models.ManyToManyField(blank=True, related_name='_notification_readed_by_+', to=settings.AUTH_USER_MODEL, verbose_name='Leido por...')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-id'],
                'permissions': [('Can_View__Notification', 'Ve notificaciones'), ('Can_Create__Notification', 'Crea notificaciones'), ('Can_Update__Notification', 'Modifica notificaciones'), ('Can_Delete__Notification', 'Elimina notificaciones')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
