# Generated by Django 2.0.5 on 2018-09-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0007_auto_20180927_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sended',
            field=models.BooleanField(default=False, help_text='Indica si esta notificación ya fue enviada.', verbose_name='Enviado?'),
        ),
    ]
