# Generated by Django 2.0.5 on 2018-09-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0008_notification_sended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Channel', 'Ve canales de comunicación'), ('Can_Create__Channel', 'Crea canales de comunicación'), ('Can_Update__Channel', 'Modifica canales de comunicación'), ('Can_Delete__Channel', 'Elimina canales de comunicación')], 'verbose_name': 'Canal de comunicación', 'verbose_name_plural': 'Canales de comunicación'},
        ),
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
