# Generated by Django 2.0.5 on 2018-09-27 22:39

from django.db import migrations, models
import mirari.INT.models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0009_auto_20180927_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.ManyToManyField(related_name='_notification_channel_+', to='INT.Channel', verbose_name='Canal(es) por donde envias'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=mirari.INT.models.path_Notification_file, verbose_name='Archivo(s) adjunto(s)'),
        ),
    ]
