# Generated by Django 2.0.5 on 2018-09-28 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0010_auto_20180927_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime_expire',
            field=models.DateTimeField(blank=True, help_text='Este mensaje expira?, dejalo vacio si no expira.', null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sended',
            field=models.BooleanField(default=False, editable=False, help_text='Indica si esta notificación ya fue enviada.', verbose_name='Enviado?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('deleted', 'Eliminado')], default='draft', max_length=250, verbose_name='Estatus'),
        ),
    ]
