# Generated by Django 2.0.5 on 2018-10-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0002_auto_20180918_1515'),
        ('INT', '0012_auto_20181001_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Canal activo'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='channel',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mirari.Organization', verbose_name='Canal(es) por donde envias'),
            preserve_default=False,
        ),
    ]
