# Generated by Django 2.0.5 on 2018-10-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0013_auto_20181001_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='message',
        ),
    ]
