# Generated by Django 2.0.5 on 2018-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0015_auto_20181001_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='name',
            field=models.CharField(default='Manual', max_length=250, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
