# Generated by Django 2.0.5 on 2018-10-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0016_handbook_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbook',
            name='is_active',
        ),
    ]
