# Generated by Django 2.0.5 on 2018-10-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0017_remove_handbook_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
