# Generated by Django 2.0.5 on 2018-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0018_handbook_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Prueba 1', max_length=250, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
