# Generated by Django 2.0.5 on 2018-10-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0020_notification_craeted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='craeted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Canal(es) por donde envias'),
        ),
    ]
