# Generated by Django 2.0.5 on 2018-10-12 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('INT', '0021_auto_20181010_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sended_to',
            field=models.ManyToManyField(blank=True, related_name='_notification_sended_to_+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado a...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
