# Generated by Django 2.0.5 on 2018-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0023_auto_20181014_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hide_content',
            field=models.BooleanField(default=True, editable=False, help_text='Si ocultas el contenido el usuario deberá ingresar usuario y contraseña para ver el contenido.', verbose_name='Ocultar contenido?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Borrador', max_length=250, verbose_name='Estatus'),
        ),
    ]
