# Generated by Django 2.0.5 on 2018-10-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0025_auto_20181025_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
