# Generated by Django 2.0.5 on 2018-10-29 22:29

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0027_auto_20181026_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='readed_by',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_notification_readed_by_+', to=settings.AUTH_USER_MODEL, verbose_name='Leido por...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sended_to',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_notification_sended_to_+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado a...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
