# Generated by Django 2.0.5 on 2018-11-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0028_auto_20181029_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='craeted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Canal(es) por donde envias'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='readed_by',
            field=models.ManyToManyField(blank=True, related_name='_notification_readed_by_+', to=settings.AUTH_USER_MODEL, verbose_name='Leido por...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sended',
            field=models.BooleanField(default=False, help_text='Indica si esta notificación ya fue enviada.', verbose_name='Enviado?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sended_to',
            field=models.ManyToManyField(blank=True, related_name='_notification_sended_to_+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado a...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
