# Generated by Django 2.0.5 on 2018-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0029_auto_20181106_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código'),
        ),
    ]
