# Generated by Django 2.0.5 on 2019-01-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0016_auto_20181219_1659'),
        ('INT', '0030_team_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del buzón')),
                ('slug', models.CharField(editable=False, max_length=250, verbose_name='Nombre del buzón')),
                ('email', models.CharField(help_text='Separa con una coma todos los correos de los destinatarios', max_length=500, verbose_name="Email's de los destinatarios")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del buzón')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Buzon Interno',
                'verbose_name_plural': 'Buzonez Internos',
                'ordering': ['-id'],
                'permissions': [('Can_View__InternalMailBox', 'Ve buzonez internos'), ('Can_Create__InternalMailBox', 'Crea buzonez internos'), ('Can_Update__InternalMailBox', 'Modifica buzonez internos'), ('Can_Delete__InternalMailBox', 'Elimina buzonez internos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
