# Generated by Django 2.0.5 on 2019-01-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0031_internalmailbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalmailbox',
            old_name='email',
            new_name='emails',
        ),
    ]
