# Generated by Django 2.0.5 on 2019-01-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0032_auto_20190108_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMailBox_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('internalmailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='INT.InternalMailBox')),
            ],
            options={
                'verbose_name': 'Email de Buzon Interno',
                'verbose_name_plural': 'Emails Buzonez Internos',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
