# Generated by Django 2.0.5 on 2019-01-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0033_internalmailbox_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmailbox',
            name='availability',
            field=models.ManyToManyField(blank=True, help_text='Si lo dejas en blanco, estara disponible para cualquier persona de la organización', related_name='_internalmailbox_availability_+', to='INT.Team', verbose_name='Disponible para estos equipos'),
        ),
        migrations.AddField(
            model_name='internalmailbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Buzón activo?'),
        ),
    ]
