# Generated by Django 2.0.5 on 2019-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0034_auto_20190109_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalmailbox',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__InternalMailBox', 'Ve buzones internos'), ('Can_Create__InternalMailBox', 'Crea buzones internos'), ('Can_Update__InternalMailBox', 'Modifica buzones internos'), ('Can_Delete__InternalMailBox', 'Elimina buzones internos')], 'verbose_name': 'Buzon Interno', 'verbose_name_plural': 'Buzones Internos'},
        ),
        migrations.AlterModelOptions(
            name='internalmailbox_mail',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Email de Buzon Interno', 'verbose_name_plural': 'Emails Buzones Internos'},
        ),
        migrations.AlterField(
            model_name='internalmailbox',
            name='availability',
            field=models.ManyToManyField(blank=True, help_text='Si lo dejas en blanco, estara disponible para cualquier persona de la organización.', related_name='_internalmailbox_availability_+', to='INT.Team', verbose_name='Disponible para estos equipos'),
        ),
        migrations.AlterField(
            model_name='internalmailbox',
            name='emails',
            field=models.CharField(help_text="Separa con ',' o ';' los correos de los destinatarios", max_length=500, verbose_name="Email's de los destinatarios"),
        ),
    ]
