# Generated by Django 2.0.5 on 2018-09-27 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mirari.CRYE.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirari', '0002_auto_20180918_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLDNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('description', models.TextField(max_length=500, verbose_name='Notas')),
                ('file', models.FileField(blank=True, null=True, upload_to=mirari.CRYE.models.path_PLDNotifications_file, verbose_name='Archivo adjunto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
                ('readed_by', models.ManyToManyField(blank=True, related_name='_pldnotifications_readed_by_+', to=settings.AUTH_USER_MODEL, verbose_name='Leido por...')),
            ],
            options={
                'verbose_name': 'Notificación PLD',
                'verbose_name_plural': 'Notificaciones PLD',
                'ordering': ['-id'],
                'permissions': [('Can_View__PLDNotifications', 'Ve notificaciones pld'), ('Can_Create__PLDNotifications', 'Crea notificaciones pld'), ('Can_Update__PLDNotifications', 'Modifica notificaciones pld'), ('Can_Delete__PLDNotifications', 'Elimina notificaciones pld')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
