# Generated by Django 2.0.5 on 2018-10-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiebelUnblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Desbloqueo Siebel',
                'verbose_name_plural': 'Desbloqueo Siebel',
                'ordering': ['-id'],
                'permissions': [('Can_View__SiebelUnblock', 'Ve desbloqueo siebel')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
