# Generated by Django 2.0.5 on 2019-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasasInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tasa de interés',
                'verbose_name_plural': 'Tasas de interés',
                'ordering': ['-id'],
                'permissions': [('Can_View__TasasInteres', 'Ve tasas de interés'), ('Can_Create__TasasInteres', 'Crea tasas de interés'), ('Can_Update__TasasInteres', 'Modifica tasas de interés'), ('Can_Delete__TasasInteres', 'Elimina tasas de interés')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WalletCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('numero', models.IntegerField(verbose_name='ID CLiente')),
                ('obligacion', models.CharField(max_length=250, verbose_name='Obligación')),
                ('clasificacion', models.CharField(max_length=250, verbose_name='Clasificación')),
                ('clasificacion_contable', models.CharField(max_length=250, verbose_name='Clasificación contable')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('rfc', models.CharField(max_length=250, verbose_name='RFC')),
                ('producto', models.CharField(max_length=250, verbose_name='Producto')),
                ('forma_pago', models.CharField(max_length=250, verbose_name='Forma de pago')),
                ('tipo_tasa', models.CharField(max_length=250, verbose_name='Tipo de tasa')),
                ('tasa', models.CharField(max_length=250, verbose_name='Tasa')),
                ('fecha_otorgado', models.DateTimeField(verbose_name='Fecha otorgado')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha vencimiento')),
                ('plazo', models.CharField(max_length=250, verbose_name='Plazo')),
                ('monto', models.CharField(max_length=250, verbose_name='Monto')),
                ('fondeador', models.CharField(max_length=250, verbose_name='Fondeador')),
            ],
            options={
                'verbose_name': 'Cartera',
                'verbose_name_plural': 'Carteras',
                'ordering': ['-id'],
                'permissions': [('Can_View__WalletCredit', 'Ve carteras'), ('Can_Create__WalletCredit', 'Crea carteras'), ('Can_Update__WalletCredit', 'Modifica carteras'), ('Can_Delete__WalletCredit', 'Elimina carteras')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
