# Generated by Django 2.0.5 on 2019-01-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0016_auto_20181219_1659'),
        ('CRYE', '0002_tasasinteres_walletcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcredit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='clasificacion_contable',
            field=models.CharField(choices=[('GARANTIZADOS CON LOS BIENES QUE DAN ORIG', 'GARANTIZADOS CON LOS BIENES QUE DAN ORIG'), ('CRÉDITO SIMPLE', 'CRÉDITO SIMPLE'), ('GARANTIZADOS CON INMUEBLES URBANOS', 'GARANTIZADOS CON INMUEBLES URBANOS'), ('QUIROGRAFARIOS', 'QUIROGRAFARIOS')], max_length=250, verbose_name='Clasificación contable'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='fecha_otorgado',
            field=models.DateField(verbose_name='Fecha otorgado'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='forma_pago',
            field=models.CharField(choices=[('INTERESES MENSUALES Y CAPITAL AL VENCIMIENTO', 'INTERESES MENSUALES Y CAPITAL AL VENCIMIENTO'), ('INTERES Y CAPITAL MENSUALMENTE', 'INTERES Y CAPITAL MENSUALMENTE'), ('INTERESES Y CAPITAL AL VENCIMIENTO', 'INTERESES Y CAPITAL AL VENCIMIENTO')], max_length=250, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='tipo_tasa',
            field=models.CharField(choices=[('FIJA', 'FIJA'), ('TIIE', 'TIIE')], max_length=250, verbose_name='Tipo de tasa'),
        ),
    ]
