# Generated by Django 2.0.5 on 2019-02-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0003_auto_20190129_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='fondeador',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fondeador'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='producto',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='rfc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='RFC'),
        ),
    ]
