# Generated by Django 2.0.5 on 2019-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0004_auto_20190131_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaAmortizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tabla de amortización',
                'verbose_name_plural': 'Tablas de amortización',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
