# Generated by Django 2.0.5 on 2019-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0005_tablaamortizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='clasificacion_contable',
            field=models.CharField(blank=True, choices=[('GARANTIZADOS CON LOS BIENES QUE DAN ORIG', 'GARANTIZADOS CON LOS BIENES QUE DAN ORIG'), ('CRÉDITO SIMPLE', 'CRÉDITO SIMPLE'), ('GARANTIZADOS CON INMUEBLES URBANOS', 'GARANTIZADOS CON INMUEBLES URBANOS'), ('QUIROGRAFARIOS', 'QUIROGRAFARIOS')], max_length=250, null=True, verbose_name='Clasificación contable'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='fecha_otorgado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha otorgado'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('INTERESES MENSUALES Y CAPITAL AL VENCIMIENTO', 'INTERESES MENSUALES Y CAPITAL AL VENCIMIENTO'), ('INTERES Y CAPITAL MENSUALMENTE', 'INTERES Y CAPITAL MENSUALMENTE'), ('INTERESES Y CAPITAL AL VENCIMIENTO', 'INTERESES Y CAPITAL AL VENCIMIENTO')], max_length=250, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='monto',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='obligacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Obligación'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='plazo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Plazo'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='tasa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tasa'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='tipo_tasa',
            field=models.CharField(blank=True, choices=[('FIJA', 'FIJA'), ('TIIE', 'TIIE')], max_length=250, null=True, verbose_name='Tipo de tasa'),
        ),
    ]
