# Generated by Django 2.0.5 on 2019-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0006_auto_20190305_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcredit',
            name='tipo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de persona'),
        ),
    ]
