# Generated by Django 2.0.5 on 2019-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0007_walletcredit_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID CLiente'),
        ),
    ]
