# Generated by Django 2.0.5 on 2019-03-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0008_auto_20190305_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='monto',
            field=models.FloatField(blank=True, max_length=250, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='plazo',
            field=models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Plazo'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='tasa',
            field=models.FloatField(blank=True, max_length=250, null=True, verbose_name='Tasa'),
        ),
    ]
