# Generated by Django 2.0.5 on 2019-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0010_auto_20190305_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaamortizacion',
            name='balanceInsoluto',
            field=models.FloatField(default=0, verbose_name='Balance Insoluto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='capital',
            field=models.FloatField(default=0, verbose_name='Capital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha otorgado'),
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='estatus',
            field=models.CharField(choices=[('Facturado', 'Facturado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=250, verbose_name='Fondeador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='intereses',
            field=models.FloatField(default=0, verbose_name='Intereses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='numeroPago',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID CLiente'),
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='pagado',
            field=models.FloatField(default=0, verbose_name='Pagado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaamortizacion',
            name='renta',
            field=models.FloatField(default=0, verbose_name='Renta'),
            preserve_default=False,
        ),
    ]
