# Generated by Django 2.0.5 on 2019-03-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0011_auto_20190306_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaamortizacion',
            name='walletcredit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRYE.WalletCredit'),
            preserve_default=False,
        ),
    ]
