# Generated by Django 2.0.5 on 2019-03-07 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRYE', '0012_tablaamortizacion_walletcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoAmortizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('capital', models.FloatField(verbose_name='Intereses')),
                ('interesVigente', models.FloatField(verbose_name='Intereses')),
                ('intereVigenteNoPagado', models.FloatField(verbose_name='Intereses')),
                ('interesMoratorio', models.FloatField(verbose_name='Intereses')),
                ('gastosCobranza', models.FloatField(verbose_name='Intereses')),
                ('iva', models.FloatField(verbose_name='Intereses')),
                ('tablaaAmortizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRYE.TablaAmortizacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de amortizacion',
                'verbose_name_plural': 'Pago de amortizacion',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
