# Generated by Django 2.0.5 on 2019-03-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0016_auto_20190325_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletcredit',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='clasificacion_contable',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='fecha_otorgado',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='fondeador',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='obligacion',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='tasa',
        ),
        migrations.RemoveField(
            model_name='walletcredit',
            name='tipo_tasa',
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID Cliente'),
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='id_solicitud',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID solicitud'),
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='interes_ordinario',
            field=models.FloatField(blank=True, null=True, verbose_name='Interés ordinario'),
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='limite_credito',
            field=models.FloatField(blank=True, null=True, verbose_name='Limite de crédito'),
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='solicitud',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='walletcredit',
            name='tipo_plazo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de plazo'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='walletcredit_tipo',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('ARRENDAMIENTO', 'ARRENDAMIENTO')], default='CREDITO', max_length=250, verbose_name='Obligación'),
        ),
    ]
