# Generated by Django 2.0.5 on 2019-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0017_auto_20190325_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcredit',
            name='id_tabla',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='id_plaza'),
        ),
        migrations.AlterField(
            model_name='walletcredit',
            name='walletcredit_tipo',
            field=models.CharField(choices=[('ARRENDAMIENTO', 'ARRENDAMIENTO'), ('CREDITO', 'CREDITO')], default='CREDITO', max_length=250, verbose_name='Obligación'),
        ),
    ]
