# Generated by Django 2.0.5 on 2019-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0019_auto_20190326_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaamortizacion',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
    ]
