# Generated by Django 2.0.5 on 2019-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0022_auto_20190327_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='walletcredit_tipo',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('ARRENDAMIENTO', 'ARRENDAMIENTO')], default='CREDITO', max_length=250, verbose_name='Tipo de cartera'),
        ),
    ]
