# Generated by Django 2.0.5 on 2020-02-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0072_auto_20190918_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='walletcredit_tipo',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('ARRENDAMIENTO', 'ARRENDAMIENTO')], default='CREDITO', max_length=250, verbose_name='Tipo de cartera'),
        ),
    ]
