# Generated by Django 2.0.5 on 2020-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYE', '0078_auto_20200318_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcredit',
            name='walletcredit_tipo',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('ARRENDAMIENTO', 'ARRENDAMIENTO')], default='CREDITO', max_length=250, verbose_name='Tipo de cartera'),
        ),
    ]
