APP = 'mirari'

GENDER = (
	('Hombre', 'Hombre'),
	('Mujer', 'Mujer'),
	('Otro', 'Otro'),
)

MENU = {
	'mirari': {
		'title': 'ORGANIZACIÓN',
		'modules': [
			{
				'title': 'ORGANIZACIóN',
				'icon': 'flaticon-map',
				'text': 'CONFIGURA TU ORGANIZACIÓN',
				'subtext': 'Administra tus organizaciones del sistema',
				'apps': ['mirari',],
				'permission': 'Can_View',
				'model': 'mirari.Organization',
				'url': 'Generic__ListView',
			},
			{
				'title': 'PERFILES',
				'icon': 'flaticon-squares-3',
				'text': 'ADMINISTRACIÓN DE PERFILES Y PERMISOS',
				'subtext': 'Configura nuevos perfiles o permisos del sistema',
				'apps': ['mirari', ],
				'permission': 'Can_View',
				'model': 'mirari.Profile',
				'url': 'Generic__ListView',
			},
			{
				'title': 'USUARIOS',
				'icon': 'flaticon-profile',
				'text': 'ADMINISTRACION DE USUARIOS',
				'subtext': 'Herramientas para la administracion de usuarios',
				'apps': ['mirari', ],
				'permission': 'Can_View',
				'model': 'mirari.User',
				'url': 'User__ListView',
			},
		]
	},
	'SV': {
		'title': 'SUVENTA',
		'modules': [
			{
				'title': 'PUNTOS DE VENTA',
				'icon': 'flaticon-piggy-bank',
				'text': 'MIS PUNTOS DE VENTA',
				'subtext': 'Administra y organiza tus Puntos de Venta',
				'apps': ['SV', ],
				'permission': 'Can_View',
				'model': 'SV.Sellpoint',
				'url': 'Generic__ListView',
			},
			{
				'title': 'MENUS',
				'icon': 'flaticon-list-1',
				'text': 'MENUS DEL PUNTO DE VENTA',
				'subtext': 'Organiza tus productos por medio de menús',
				'apps': ['SV', ],
				'permission': 'Can_View',
				'model': 'SV.Menu',
				'url': 'Generic__ListView',
			},
			{
				'title': 'PRODUCTOS',
				'icon': 'flaticon-open-box',
				'text': 'LISTADO DE PRODUCTOS',
				'subtext': 'Listado de productos que se ofertan en el PV',
				'apps': ['SV', ],
				'permission': 'Can_View',
				'model': 'SV.Product',
				'url': 'Generic__ListView',
			},
			{
				'title': 'ACCESO AL PV',
				'icon': 'flaticon-lock',
				'text': 'LISTADO DE ACCESOS DE EMPLEADOS',
				'subtext': 'Listado de todos los permisos de los empleados',
				'apps': ['SV', ],
				'permission': 'Can_View',
				'model': 'SV.EmployeeAccess',
				'url': 'Generic__ListView',
			},
			#{
                				#'title': 'PUNTOS DE VENTA',
                				#'icon': 'flaticon-piggy-bank',
                				#'text': 'MIS PUNTOS DE VENTA',
                				#'subtext': 'Administra y organiza tus Puntos de Venta',
                				#'apps': ['SuVenta',],
                				#'permission': 'Can_View',
                				#'model': 'SuVenta.SellpointSuVenta',
                				#'url': '_ListView',
                				#'keys': 'puntos de venta',
			#},
			#{
                				#'title': 'MENUS',
                				#'icon': 'flaticon-list-1',
                				#'text': 'MENUS del PV',
                				#'subtext': 'Organiza tus productos por medio de menús',
                				#'apps': ['SuVenta',],
                				#'permission': 'Can_View',
                				#'model': 'SuVenta.MenuSuVenta',
                				#'url': '_ListView',
                				#'keys': 'menu',
			#},

			##{
                				##'title': 'TICKETS',
                				##'icon': 'flaticon-interface-10',
                				##'text': 'LISTADO DE TICKETS',
                				##'subtext': 'Listado de tickets',
                				##'apps': '',
                				##'permission': 'Can_View',
                				##'model': 'SuVenta.TicketSuVenta',
                				##'url': '_ListView',
                				##'keys': 'ticket',
			##},
			##{
                				##'title': 'CORTES',
                				##'icon': 'flaticon-interface-10',
                				##'text': 'CORTES DEL SISTEMA',
                				##'subtext': 'Listado de cortes',
                				##'apps': '',
                				##'permission': 'Can_View',
                				##'model': 'SuVenta.CutSuVenta',
                				##'url': '_ListView',
                				##'keys': 'corte',
			##},
		]
	},
	#'Intranet': {
		#'title': 'INTRANET',
		#'modules': [
			#{
				#'title': 'EMPLEADOS',
				#'icon': 'la la-users',
				#'text': 'LISTADO DE EMPLEADOS',
				#'subtext': 'Lista de empleados de la organización',
				#'apps': ['Intranet', ],
				#'permission_': 'Can_View__Employees',
				#'model': 'mirari.User',
				#'url_': 'Intranet:Employees_ListView',
				#'keys': 'user',
			#},
			#{
				#'title': 'EQUIPOS',
				#'icon': 'flaticon-users',
				#'text': 'ORGANIZACIÓN DE EQUIPOS',
				#'subtext': 'Crea equipos de trabajo en el sistema',
				#'apps': ['Intranet', ],
				#'permission': 'Can_View',
				#'model': 'Intranet.Team',
				#'url': '_ListView',
				#'keys': 'team',
			#},
			#{
				#'title': 'CATÁLOGOS',
				#'icon': 'flaticon-file-1',
				#'text': 'ADMINISTRACIÓN DE DOCUMENTOS',
				#'subtext': 'Administrador de documentos en la organización',
				#'apps': ['Intranet', ],
				#'permission': 'Can_View',
				#'model': 'Intranet.Catalogue',
				#'url': '_ListView',
				#'keys': 'catálogo',
			#},
			#{
				#'title': 'MANUALES',
				#'icon': 'flaticon-interface-5',
				#'text': 'DESCARGA DE MANUALES DE OPERACIÓN',
				#'subtext': 'Manuales de operacion de la organización',
				#'apps': ['Intranet', ],
				#'permission': 'Can_View',
				#'model': 'Intranet.Manual',
				#'url': '_ListView',
				#'keys': 'catálogo',
			#},
		#]
	#},
	#'PartnerLenders': {
		#'title': 'SOCIOS PRESTAMISTAS',
		#'modules': [
			#{
				#'title': 'SOCIOS PRESTAMISTAS',
				#'icon': 'flaticon-user-ok',
				#'text': 'LISTADO DE SOCIOS',
				#'subtext': 'Lista de los socios prestamistas en el sistema.',
				#'apps': ['PartnerLenders', ],
				#'permission': 'Can_View',
				#'model': 'PartnerLenders.PartnerLender',
				#'url': '_ListView',
				#'keys': 'socios, prestamistas',
			#},
		#]
	#},
	#'CryE': {
		#'title': 'CREDIPyME APPs',
		#'modules': [
			#{
				#'title': 'SIEBEL',
				#'icon': 'flaticon-more-v4',
				#'text': 'FUNCIONES DE SIEBEL PARA EL USUARIO',
				#'subtext': 'Conjunto de funciones para sistema SIEBEL',
				#'apps': ['CryE', ],
				#'permission': 'Can_View',
				#'model': 'CryE.SiebelCryE',
				#'url': '_TemplateView',
				#'keys': 'siebel,',
			#},
		#]
	#},
	#'SuVenta': {
		#'title': 'SUVENTA',
		#'modules': [
			#{
				#'title': 'PUNTOS DE VENTA',
				#'icon': 'flaticon-piggy-bank',
				#'text': 'MIS PUNTOS DE VENTA',
				#'subtext': 'Administra y organiza tus Puntos de Venta',
				#'apps': ['SuVenta', ],
				#'permission': 'Can_View',
				#'model': 'SuVenta.SellpointSuVenta',
				#'url': '_ListView',
				#'keys': 'puntos de venta',
			#},
			#{
				#'title': 'MENUS',
				#'icon': 'flaticon-list-1',
				#'text': 'MENUS DEL PUNTO DE VENTA',
				#'subtext': 'Organiza tus productos por medio de menús',
				#'apps': ['SuVenta', ],
				#'permission': 'Can_View',
				#'model': 'SuVenta.MenuSuVenta',
				#'url': '_ListView',
				#'keys': 'menu',
			#},
			#{
				#'title': 'PRODUCTOS',
				#'icon': 'flaticon-open-box',
				#'text': 'LISTADO DE PRODUCTOS',
				#'subtext': 'Listado de productos que se ofertan en el PV',
				#'apps': ['SuVenta', ],
				#'permission': '',
				#'model': 'SuVenta.ProductSuVenta',
				#'url': '_ListView',
				#'keys': 'producto',
			#},
			##{
                				##'title': 'PUNTOS DE VENTA',
                				##'icon': 'flaticon-piggy-bank',
                				##'text': 'MIS PUNTOS DE VENTA',
                				##'subtext': 'Administra y organiza tus Puntos de Venta',
                				##'apps': ['SuVenta',],
                				##'permission': 'Can_View',
                				##'model': 'SuVenta.SellpointSuVenta',
                				##'url': '_ListView',
                				##'keys': 'puntos de venta',
			##},
			##{
                				##'title': 'MENUS',
                				##'icon': 'flaticon-list-1',
                				##'text': 'MENUS del PV',
                				##'subtext': 'Organiza tus productos por medio de menús',
                				##'apps': ['SuVenta',],
                				##'permission': 'Can_View',
                				##'model': 'SuVenta.MenuSuVenta',
                				##'url': '_ListView',
                				##'keys': 'menu',
			##},
#
			###{
                				###'title': 'TICKETS',
                				###'icon': 'flaticon-interface-10',
                				###'text': 'LISTADO DE TICKETS',
                				###'subtext': 'Listado de tickets',
                				###'apps': '',
                				###'permission': 'Can_View',
                				###'model': 'SuVenta.TicketSuVenta',
                				###'url': '_ListView',
                				###'keys': 'ticket',
			###},
			###{
                				###'title': 'CORTES',
                				###'icon': 'flaticon-interface-10',
                				###'text': 'CORTES DEL SISTEMA',
                				###'subtext': 'Listado de cortes',
                				###'apps': '',
                				###'permission': 'Can_View',
                				###'model': 'SuVenta.CutSuVenta',
                				###'url': '_ListView',
                				###'keys': 'corte',
			###},
		#]
	#},
}
