OrderedDict([('ns:LVP_spcConsulta_spcSR_Output',
              OrderedDict([('@xmlns:ns', 'http://siebel.com/CustomUI'),
                           ('ns:Error_spcCode', None),
                           ('ns:Error_spcMessage', None),
                           ('ListOfLvpServiceRequestIo',
                            OrderedDict([('@xmlns',
                                          'http://www.siebel.com/xml/LVP%20Service%20Request%20IO'),
                                         ('LvpServiceRequestCustom',
                                          [OrderedDict([('Abstract',
                                                         'CLIENTE SOLICITA CONEXION BICICLETA'),
                                                        ('ContactFirstName',
                                                         'FLOR'),
                                                        ('ContactLastName',
                                                         'DE LUZ VERA'),
                                                        ('INSArea',
                                                         'Aparatos de Ejercicio'),
                                                        ('INSSub-Area',
                                                         'Conexión/Demostración CS'),
                                                        ('LVPAssetModel',
                                                         'GX2.7'),
                                                        ('LVPCity',
                                                         'VERACRUZ DE IGNACIO DE LA LLAV'),
                                                        ('LVPContactPhone',
                                                         '782-1693335'),
                                                        ('LVPContacteMail',
                                                         'ggusa@gmail.com'),
                                                        ('LVPCountry',
                                                         'MEXICO'),
                                                        ('LVPCreatedBy',
                                                         '1-6KDVKE0'),
                                                        ('LVPPostalCode',
                                                         '093230'),
                                                        ('LVPProvince',
                                                         'CAZONES'),
                                                        ('LVPState',
                                                         'POZA RICA DE HIDALGO'),
                                                        ('LVPStreetAddress',
                                                         '8 407'),
                                                        ('LVPType4thLevel',
                                                         'Garantía'),
                                                        ('OpenedDate',
                                                         '18/03/2020 09:41:41'),
                                                        ('SRId', '1-6PC238L'),
                                                        ('SRNumber',
                                                         '1-14592601317'),
                                                        ('SerialNumber',
                                                         '94858495'),
                                                        ('ShipDate',
                                                         '25/03/2020')]),
                                           OrderedDict([('Abstract',
                                                         'CLIENTE SOLICITA MANTENIMIENTO MAQUINA DE REMO'),
                                                        ('ContactFirstName',
                                                         'MARIBEL'),
                                                        ('ContactLastName',
                                                         'MAGANA'),
                                                        ('INSArea',
                                                         'Aparatos de Ejercicio'),
                                                        ('INSSub-Area',
                                                         'Mantenimiento CS'),
                                                        ('LVPAssetModel',
                                                         'Full Motion'),
                                                        ('LVPCity', 'TABASCO'),
                                                        ('LVPContactPhone',
                                                         '993-3259093'),
                                                        ('LVPContacteMail',
                                                         'mary-picis@hotmail.com'),
                                                        ('LVPCountry',
                                                         'MEXICO'),
                                                        ('LVPCreatedBy',
                                                         '1-6KDVKE0'),
                                                        ('LVPPostalCode',
                                                         '86220'),
                                                        ('LVPProvince',
                                                         'EL CARMEN'),
                                                        ('LVPState',
                                                         'NACAJUCA'),
                                                        ('LVPStreetAddress',
                                                         '16 DE SEPTIEMBRE SN'),
                                                        ('LVPType4thLevel',
                                                         'Cargo'),
                                                        ('OpenedDate',
                                                         '18/03/2020 10:34:21'),
                                                        ('SRId', '1-6PC239Y'),
                                                        ('SRNumber',
                                                         '1-14592601366'),
                                                        ('SerialNumber',
                                                         '84754858'),
                                                        ('ShipDate',
                                                         '10/04/2020')])])]))]))])