# Generated by Django 2.0.5 on 2018-11-07 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirari', '0007_auto_20181025_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Brand')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Order_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Nueva', 'Nueva'), ('Alerta', 'Alerta'), ('Espera de refacciones', 'Espera de refacciones'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada'), ('Especial', 'Especial')], max_length=250)),
                ('service', models.CharField(choices=[('Icon', 'Icon'), ('Tecnoservicio', 'Tecnoservicio')], default='Icon', max_length=250)),
                ('zone', models.CharField(choices=[('Local', 'Local'), ('Foraneo', 'Foraneo')], default='Local', max_length=250)),
                ('concept', models.CharField(choices=[('Armado', 'Armado'), ('Revision', 'Revision'), ('OrdenesIcon', 'OrdenesIcon'), ('Mantenimiento', 'Mantenimiento'), ('Servicio', 'Servicio')], default='Armado', max_length=250)),
                ('service_date', models.DateField()),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('contact_phone1', models.CharField(blank=True, max_length=250)),
                ('contact_phone2', models.CharField(blank=True, max_length=250)),
                ('street', models.CharField(blank=True, max_length=500)),
                ('street_notes', models.TextField(blank=True, max_length=250)),
                ('reporta', models.CharField(max_length=250)),
                ('serial_number', models.CharField(blank=True, max_length=250)),
                ('hidden_notes', models.TextField(blank=True)),
                ('order_notes', models.TextField(blank=True, verbose_name='Comentarios impresos')),
                ('icon_os', models.CharField(blank=True, max_length=250)),
                ('icon_ics', models.CharField(blank=True, max_length=250, verbose_name='icon ics 1')),
                ('icon_ics_2', models.CharField(blank=True, default='', max_length=250, verbose_name='icon ics 2')),
                ('icon_ics_3', models.CharField(blank=True, default='', max_length=250, verbose_name='icon ics 3')),
                ('icon_on', models.CharField(blank=True, max_length=250)),
                ('icon_cn', models.CharField(blank=True, max_length=250)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Brand')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Modelo')),
                ('serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Ordenes de servicio',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='order_service',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Store'),
        ),
        migrations.AddField(
            model_name='order_service',
            name='technical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='store',
            field=models.ManyToManyField(to='TCS.Store'),
        ),
    ]
