# Generated by Django 2.0.5 on 2018-11-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0006_auto_20181115_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='report_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nombre de quien reporta'),
        ),
    ]
