# Generated by Django 2.0.5 on 2019-01-24 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TCS', '0010_remove_orderservice_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas <small>(Impresas en la orden)</small>')),
                ('orderservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TCS.OrderService')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Orden',
                'verbose_name_plural': 'Historial de Ordenes',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
