# Generated by Django 2.0.5 on 2019-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0011_orderservicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='hidden_notes',
            field=models.TextField(blank=True, verbose_name='Notas OCULTAS<small>(No se imprimen en la orden)</small>'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='order_notes',
            field=models.TextField(blank=True, verbose_name='Notas IMPRESAS<small>(Impresas en la orden)</small>'),
        ),
    ]
