# Generated by Django 2.0.5 on 2019-02-20 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TCS', '0012_auto_20190129_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Comentario de Orden',
                'verbose_name_plural': 'Comentarios de Orden',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='status',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Alerta', 'Alerta'), ('Espera de refacciones', 'Espera de refacciones'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada'), ('Especial', 'Especial')], default='Nueva', max_length=250, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='orderservicecomment',
            name='orderservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TCS.OrderService'),
        ),
        migrations.AddField(
            model_name='orderservicecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
