# Generated by Django 2.0.5 on 2019-02-21 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0013_auto_20190220_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicecomment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
