# Generated by Django 2.0.5 on 2019-02-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TCS', '0014_orderservicecomment_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('concept', models.CharField(blank=True, max_length=250)),
                ('quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('orderservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TCS.OrderService')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concepto de Orden',
                'verbose_name_plural': 'Conceptos de Orden',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
