# Generated by Django 2.0.5 on 2019-02-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0015_orderserviceconcept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderserviceconcept',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__OrderServiceConcept', 'Ve conceptos de orden'), ('Can_Create__OrderServiceConcept', 'Crea conceptos de orden'), ('Can_Update__OrderServiceConcept', 'Modifica conceptos de orden'), ('Can_Delete__OrderServiceConcept', 'Elimina conceptos de orden')], 'verbose_name': 'Concepto de Orden', 'verbose_name_plural': 'Conceptos de Orden'},
        ),
    ]
