# Generated by Django 2.0.5 on 2019-02-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0016_auto_20190225_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='id_bckp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='id_bckp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.CharField(choices=[('Icon', 'Icon'), ('Tecnoservicio', 'Tecnoservicio'), ('Tc2', 'Tc2')], default='Icon', max_length=250, verbose_name='Tipo de servicio'),
        ),
    ]
