# Generated by Django 2.0.5 on 2019-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0017_auto_20190226_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id_bckp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='id_bckp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderservice',
            name='id_bckp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
