# Generated by Django 2.0.5 on 2019-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0023_auto_20190227_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
