# Generated by Django 2.0.5 on 2019-02-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0028_auto_20190228_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Brand', 'Ve marcas'), ('Can_Create__Brand', 'Crea marcas'), ('Can_Update__Brand', 'Modifica marcas'), ('Can_Delete__Brand', 'Elimina marcas')], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Company', 'Ve empresas'), ('Can_Create__Company', 'Crea empresas'), ('Can_Update__Company', 'Modifica empresas'), ('Can_Delete__Company', 'Elimina empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Modelo', 'Ve modelos'), ('Can_Create__Modelo', 'Crea modelos'), ('Can_Update__Modelo', 'Modifica modelos'), ('Can_Delete__Modelo', 'Elimina modelos')], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='orderservicecomment',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__OrderServiceComment', 'Ve comentarios de orden'), ('Can_Create__OrderServiceComment', 'Crea comentarios de orden'), ('Can_Update__OrderServiceComment', 'Modifica comentarios de orden'), ('Can_Delete__OrderServiceComment', 'Elimina comentarios de orden')], 'verbose_name': 'Comentario de Orden', 'verbose_name_plural': 'Comentarios de Orden'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Store', 'Ve tiendas'), ('Can_Create__Store', 'Crea tiendas'), ('Can_Update__Store', 'Modifica tiendas'), ('Can_Delete__Store', 'Elimina tiendas')], 'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
    ]
