# Generated by Django 2.0.5 on 2019-02-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0030_brand_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
            preserve_default=False,
        ),
    ]
