# Generated by Django 2.0.5 on 2019-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0035_auto_20190703_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderserviceconcept',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
