# Generated by Django 2.0.5 on 2019-07-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0038_orderserviceinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderserviceinformation',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Modelo', 'Ve informacion de orden')], 'verbose_name': 'Informacion de Orden', 'verbose_name_plural': 'Informacion de Orden'},
        ),
    ]
