# Generated by Django 2.0.5 on 2019-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0040_auto_20190726_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderserviceconcept',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderservicehistory',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
