# Generated by Django 2.0.5 on 2019-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0045_auto_20190805_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
