# Generated by Django 2.0.5 on 2019-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0047_auto_20190807_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderservicecomment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderserviceconcept',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
