# Generated by Django 2.0.5 on 2019-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0049_auto_20190824_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='concept',
            field=models.CharField(choices=[('Armado', 'Armado'), ('Revision', 'Revision'), ('OrdenesIcon', 'OrdenesIcon'), ('Mantenimiento', 'Mantenimiento'), ('Servicio', 'Servicio'), ('Venta', 'Venta')], default='Armado', max_length=250, verbose_name='Concepto'),
        ),
    ]
