# Generated by Django 2.0.5 on 2020-02-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0050_auto_20190918_1247'),
        ('TCS', '0050_auto_20191127_2331'),
    ]

    operations = [
    ]
