# Generated by Django 2.0.5 on 2020-03-04 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TCS', '0052_orderservicereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservicereport',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__OrderServiceReport', 'Ve reportes de ordenes')], 'verbose_name': 'Reporte de Orden', 'verbose_name_plural': 'Reportes de Ordenes'},
        ),
        migrations.AddField(
            model_name='orderservicereport',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='orderservicereport',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='orderservicereport',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCS.Store', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='orderservicereport',
            name='technical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico'),
        ),
    ]
