# Generated by Django 2.0.5 on 2020-03-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0053_auto_20200303_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservicereport',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__OrderServiceReport', 'Ve reportes de ordenes'), ('Can_Create__OrderServiceReport', 'Crea reportes de ordenes')], 'verbose_name': 'Reporte de Orden', 'verbose_name_plural': 'Reportes de Ordenes'},
        ),
    ]
