# Generated by Django 2.0.5 on 2020-04-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0054_auto_20200304_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverpoolTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('consultaTickets', models.TextField(blank=True, verbose_name='Consulta Tickets')),
                ('consultaActividades', models.TextField(blank=True, verbose_name='Consulta Actividades')),
                ('consultaNotas', models.TextField(blank=True, verbose_name='Consulta Notas')),
                ('actualizarTickets', models.TextField(blank=True, verbose_name='Actualizar Tickets')),
                ('actualizarActividades', models.TextField(blank=True, verbose_name='Actualizar Actividades')),
                ('actualizarNotas', models.TextField(blank=True, verbose_name='Actualizar Notas')),
            ],
            options={
                'verbose_name': 'Herramienta Liverpool',
                'abstract': False,
                'permissions': [('Can_View__LiverpoolTools', 'Ve herramientas liverpool'), ('Can_Create__LiverpoolTools', 'Crea herramientas liverpool')],
                'verbose_name_plural': 'Herramientas Liverpool',
                'default_permissions': [],
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='orderservice',
            name='serialLiverpool',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Liverpool ID'),
        ),
    ]
