# Generated by Django 2.0.5 on 2018-12-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0012_remove_user_first_login'),
        ('SIEBEL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AddField(
            model_name='credit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
