# Generated by Django 2.0.5 on 2018-12-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0013_auto_20181207_1502'),
        ('SIEBEL', '0002_auto_20181203_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SIEBEL.Actor')),
            ],
            options={
                'verbose_name': 'CreditActor',
                'verbose_name_plural': 'CreditActor',
                'ordering': ['-id'],
                'permissions': [('Can_View__CreditActor', 'Ve creditactor'), ('Can_Create__CreditActor', 'Crea creditactor'), ('Can_Update__CreditActor', 'Modifica creditactor'), ('Can_Delete__CreditActor', 'Elimina creditactor')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-id'],
                'permissions': [('Can_View__Person', 'Ve personas'), ('Can_Create__Person', 'Crea personas'), ('Can_Update__Person', 'Modifica personas'), ('Can_Delete__Person', 'Elimina personas')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SIEBELCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('stage', models.CharField(editable=False, max_length=255, verbose_name='Etapa del crédito')),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'ordering': ['-id'],
                'permissions': [('Can_View__SIEBELCredit', 'Ve creditos'), ('Can_Create__SIEBELCredit', 'Crea creditos'), ('Can_Update__SIEBELCredit', 'Modifica creditos'), ('Can_Delete__SIEBELCredit', 'Elimina creditos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.RenameModel(
            old_name='Credit',
            new_name='CreditType',
        ),
        migrations.AlterModelOptions(
            name='credittype',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__CreditType', 'Ve credito'), ('Can_Create__CreditType', 'Crea credito'), ('Can_Update__CreditType', 'Modifica credito'), ('Can_Delete__CreditType', 'Elimina credito')], 'verbose_name': 'Credito', 'verbose_name_plural': 'Credito'},
        ),
        migrations.AddField(
            model_name='siebelcredit',
            name='creditType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SIEBEL.CreditType'),
        ),
        migrations.AddField(
            model_name='siebelcredit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AddField(
            model_name='creditactor',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SIEBEL.SIEBELCredit'),
        ),
        migrations.AddField(
            model_name='creditactor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SIEBEL.Person'),
        ),
    ]
