# Generated by Django 2.0.5 on 2018-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIEBEL', '0004_auto_20181210_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcredit',
            name='stage',
            field=models.CharField(max_length=255, verbose_name='Etapa del crédito'),
        ),
    ]
