# Generated by Django 2.0.5 on 2018-09-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('profiles', models.CharField(choices=[('supervisor', 'Supervisor'), ('vendor', 'Vendedor'), ('casher', 'Cajero')], max_length=30, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Acceso de empleado',
                'verbose_name_plural': 'Accesos de empleados',
                'ordering': ['-id'],
                'permissions': [('Can_View__EmployeeAccess', 'Ve accesos de empleados'), ('Can_Create__EmployeeAccess', 'Crea accesos de empleados'), ('Can_Update__EmployeeAccess', 'Modifica accesos de empleados'), ('Can_Delete__EmployeeAccess', 'Elimina accesos de empleados')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del menú')),
                ('color', models.CharField(default='#3d3b56', max_length=100, verbose_name='Color del menú')),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva todos los productos de un menú', verbose_name='Esta activo?')),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-id'],
                'permissions': [('Can_View__Menu', 'Ve menus'), ('Can_Create__Menu', 'Crea menus'), ('Can_Update__Menu', 'Modifica menus'), ('Can_Delete__Menu', 'Elimina menus')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del producto')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar producto?', verbose_name='Esta activo?')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-id'],
                'permissions': [('Can_View__Product', 'Ve productos'), ('Can_Create__Product', 'Crea productos'), ('Can_Update__Product', 'Modifica productos'), ('Can_Delete__Product', 'Elimina productos')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('alias', models.CharField(blank=True, default='', help_text='Nombre con el que se imprime este producto', max_length=250, null=True)),
                ('price', models.FloatField(default=0, verbose_name='Precio en esta sucursal')),
                ('iva', models.BooleanField(default=True, help_text='Graba IVA?', verbose_name='I.V.A.')),
                ('ieps', models.BooleanField(default=True, help_text='Graba IEPS?', verbose_name='IEPS.')),
                ('bar_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Código de Barras')),
                ('is_dynamic', models.BooleanField(default=False, help_text='Este producto tiene precio variable?', verbose_name='Precio dinámico')),
                ('is_favorite', models.BooleanField(default=False, help_text='Se muestra siempre este producto?', verbose_name='Es favorito?')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar producto?', verbose_name='Esta activo?')),
            ],
            options={
                'verbose_name': 'Atributo de producto',
                'verbose_name_plural': 'Atributos de producto',
                'ordering': ['-id'],
                'permissions': [('Can_View__ProductAttributes', 'Ve atributos de producto'), ('Can_Create__ProductAttributes', 'Crea atributos de producto'), ('Can_Update__ProductAttributes', 'Modifica atributos de producto'), ('Can_Delete__ProductAttributes', 'Elimina atributos de producto')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Sellpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del punto de venta')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('have_cashier', models.BooleanField(default=False, help_text='Tienes vendedores autorizados para cobrar en esta sucursal?', verbose_name='Cobran vendedores?')),
                ('color', models.CharField(default='#191919', max_length=50, verbose_name='Color del Punto de Venta')),
                ('number_tickets', models.IntegerField(default=1, verbose_name='Numero de tickets que imprime')),
                ('header_line_black_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Linea 1 del encabezado del ticket')),
                ('header_line_black_2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Linea 2 del encabezado del ticket')),
                ('header_line_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Linea 1 del texto del ticket')),
                ('header_line_2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Linea 2 del texto del ticket')),
                ('footer_line_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Linea 1 del pie del ticket')),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva este punto de venta', verbose_name='Esta activo?')),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
                'ordering': ['-id'],
                'permissions': [('Can_View__Sellpoint', 'Ve puntos de venta'), ('Can_Create__Sellpoint', 'Crea puntos de venta'), ('Can_Update__Sellpoint', 'Modifica puntos de venta'), ('Can_Delete__Sellpoint', 'Elimina puntos de venta')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
