# Generated by Django 2.0.5 on 2018-09-11 20:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SV', '0001_initial'),
        ('mirari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='serial',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='SV.Product'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='sellpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sellpoint', to='SV.Sellpoint'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ForeignKey(blank=True, help_text='Código de registro ante el SAT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mirari.ProductsServicesSAT', verbose_name='Código de producto en el SAT'),
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(help_text='Elige el menú donde se vende este producto', on_delete=django.db.models.deletion.PROTECT, to='SV.Menu', verbose_name=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Se vende en estas sucursales', related_name='_product_sellpoints_+', to='SV.Sellpoint', verbose_name=''),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.ForeignKey(blank=True, help_text='Unidad de medida para este producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mirari.UnitsCodesSat', verbose_name='Código de unidad en el SAT'),
        ),
        migrations.AddField(
            model_name='menu',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirari.Organization'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Elige otro menú solo si este menú depende de otro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SV.Menu', verbose_name=''),
        ),
    ]
