# Generated by Django 2.0.5 on 2018-09-18 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SV', '0003_auto_20180917_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='cashers',
            field=models.ManyToManyField(blank=True, related_name='_sellpoint_cashers_+', to=settings.AUTH_USER_MODEL, verbose_name='Cajeros'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='_sellpoint_vendors_+', to=settings.AUTH_USER_MODEL, verbose_name='Vendedores'),
        ),
    ]
