# Generated by Django 2.0.5 on 2019-03-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0006_auto_20190310_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Cut', 'Ve cortes')], 'verbose_name': 'Corte', 'verbose_name_plural': 'Cortes'},
        ),
        migrations.AlterModelOptions(
            name='productattributes',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Atributo de producto', 'verbose_name_plural': 'Atributos de producto'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketproducts',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [], 'verbose_name': 'Producto del ticket', 'verbose_name_plural': 'Productos del ticket'},
        ),
    ]
