# Generated by Django 2.0.5 on 2019-03-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0007_auto_20190310_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketproducts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
