# Generated by Django 2.0.5 on 2019-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0008_auto_20190310_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='printer',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Impresora ID'),
        ),
    ]
