# Generated by Django 2.0.5 on 2019-03-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0026_remove_profile_y'),
        ('SV', '0009_sellpoint_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('discounntType', models.CharField(choices=[('productPercent', 'Porcentaje del producto'), ('productValue', 'Valor fijo del producto')], default='% del producto', max_length=250, verbose_name='Forma de aplicar el descuento')),
                ('discounntValue', models.PositiveIntegerField(verbose_name='Valor del descuento')),
                ('conditionType', models.CharField(choices=[('productPercent', 'Porcentaje del producto'), ('productValue', 'Valor fijo del producto')], default='% del producto', max_length=250, verbose_name='Forma de aplicar el descuento')),
                ('conditionValue', models.PositiveIntegerField(verbose_name='Valor del descuento')),
                ('initialDate', models.DateTimeField(blank=True, null=True)),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar Descuento?', verbose_name='Esta activo?')),
                ('conditionMenus', models.ManyToManyField(blank=True, related_name='_offers_conditionMenus_+', to='SV.Menu', verbose_name='Menus que generan el descuento')),
                ('conditionProducts', models.ManyToManyField(blank=True, related_name='_offers_conditionProducts_+', to='SV.Product', verbose_name='Productos que generan el descuento')),
                ('disccountMenus', models.ManyToManyField(blank=True, related_name='_offers_disccountMenus_+', to='SV.Menu', verbose_name='Menus a los que afecta el descuento')),
                ('disccountProducts', models.ManyToManyField(blank=True, related_name='_offers_disccountProducts_+', to='SV.Product', verbose_name='Productos a los que afecta el descuento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-id'],
                'permissions': [],
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
