# Generated by Django 2.0.5 on 2019-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0010_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='nombre',
            field=models.CharField(default='NoName', max_length=250, verbose_name='Nombre del descuento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='finalDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='initialDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicial'),
        ),
    ]
