# Generated by Django 2.0.5 on 2019-03-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0011_auto_20190312_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='nombre',
            new_name='name',
        ),
    ]
