# Generated by Django 2.0.5 on 2019-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0013_auto_20190312_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='sellpoint',
            field=models.ManyToManyField(blank=True, related_name='_offers_sellpoint_+', to='SV.Sellpoint', verbose_name='Puntos de venta que afecta'),
        ),
    ]
