# Generated by Django 2.0.5 on 2019-03-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0026_remove_profile_y'),
        ('SV', '0014_offers_sellpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mirari.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='conditionMenus',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno usa los mismos que afecta el descuento', related_name='_offers_conditionMenus_+', to='SV.Menu', verbose_name='Menus que generan el descuento'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='conditionProducts',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno usa los mismos que afecta el descuento', related_name='_offers_conditionProducts_+', to='SV.Product', verbose_name='Productos que generan el descuento'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='sellpoint',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno afecta a todas', related_name='_offers_sellpoint_+', to='SV.Sellpoint', verbose_name='Puntos de venta que afect'),
        ),
    ]
