# Generated by Django 2.0.5 on 2019-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0015_auto_20190312_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='discounntType',
            new_name='discountType',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='discounntValue',
            new_name='discountValue',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='disccountMenus',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='disccountProducts',
        ),
        migrations.AddField(
            model_name='offers',
            name='discountMenus',
            field=models.ManyToManyField(blank=True, related_name='_offers_discountMenus_+', to='SV.Menu', verbose_name='Menus a los que afecta el descuento'),
        ),
        migrations.AddField(
            model_name='offers',
            name='discountProducts',
            field=models.ManyToManyField(blank=True, related_name='_offers_discountProducts_+', to='SV.Product', verbose_name='Productos a los que afecta el descuento'),
        ),
    ]
