# Generated by Django 2.0.5 on 2019-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0016_auto_20190312_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='sellpoint',
        ),
        migrations.AddField(
            model_name='offers',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno afecta a todas', related_name='_offers_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta que afect'),
        ),
    ]
