# Generated by Django 2.0.5 on 2019-03-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0018_auto_20190313_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellpoint',
            name='have_cashier',
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='have_casher',
            field=models.BooleanField(default=False, help_text='Tienes vendedores autorizados para cobrar en esta sucursal?', verbose_name='Tiene Caja?'),
        ),
    ]
