# Generated by Django 2.0.5 on 2019-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0019_auto_20190315_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Ticket', 'Ve tickets'), ('Can_Delete__Ticket', 'Elimina tickets')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
