# Generated by Django 2.0.5 on 2019-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0021_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sellpoint',
        ),
        migrations.AddField(
            model_name='client',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno afecta a todas', related_name='_client_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta en donde factura'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno afecta a todas', related_name='_offer_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta que afecta'),
        ),
    ]
