# Generated by Django 2.0.5 on 2019-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0022_auto_20190325_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Si no eliges ninguno afecta a todas', related_name='_client_sellpoints_+', to='SV.Sellpoint', verbose_name='Donde factura? '),
        ),
    ]
