# Generated by Django 2.0.5 on 2019-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0024_client_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivar Cliente?', verbose_name='Esta activo?'),
        ),
    ]
