# Generated by Django 2.0.5 on 2019-03-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0025_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contacto',
            new_name='contact',
        ),
    ]
