# Generated by Django 2.0.5 on 2019-03-27 22:25

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0027_auto_20190327_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, help_text='Email de contacto', max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=10, null=True, verbose_name='Correo o teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=localflavor.mx.models.MXRFCField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
