# Generated by Django 2.0.5 on 2019-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0028_auto_20190327_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC', max_length=15, null=True, verbose_name=''),
        ),
    ]
