# Generated by Django 2.0.5 on 2019-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0029_auto_20190327_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contacto', max_length=255, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto a 10 digitos', max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC de facturación', max_length=15, null=True, verbose_name='RFC'),
        ),
    ]
