# Generated by Django 2.0.5 on 2019-03-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0030_auto_20190327_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='haveCredit',
            field=models.BooleanField(default=True, verbose_name='Tiene crédito?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='haveReturn',
            field=models.BooleanField(default=True, verbose_name='Puede devolver='),
        ),
    ]
