# Generated by Django 2.0.5 on 2019-04-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0027_auto_20190319_1636'),
        ('SV', '0033_auto_20190406_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del perfil')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
            ],
            options={
                'verbose_name': 'Perfil cliente',
                'verbose_name_plural': 'Perfiles de cliente',
                'ordering': ['-id'],
                'permissions': [('Can_View__ClientProfile', 'Ve perfiles de cliente'), ('Can_Create__ClientProfile', 'Crea perfiles de cliente'), ('Can_Update__ClientProfile', 'Modifica perfiles de cliente'), ('Can_Delete__ClientProfile', 'Elimina perfiles de cliente')],
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='clientProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='SV.ClientProfile', verbose_name='Perfil de cliente'),
        ),
    ]
