# Generated by Django 2.0.5 on 2019-04-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0036_auto_20190406_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='payment',
            new_name='onAccount',
        ),
    ]
