# Generated by Django 2.0.5 on 2019-04-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0037_auto_20190406_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='clientID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
