# Generated by Django 2.0.5 on 2019-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0040_client_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='ras',
            new_name='rasurado',
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rasurado',
            field=models.BooleanField(default=False),
        ),
    ]
