# Generated by Django 2.0.5 on 2019-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0044_clientprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de cliente'),
        ),
    ]
