# Generated by Django 2.0.5 on 2019-04-15 16:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('SV', '0046_auto_20190410_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='conditionType',
            field=models.CharField(choices=[('productQuantity', 'Cantidad de productos mínima'), ('productValue', 'Valor fijo del producto')], default='productQuantity', max_length=250, verbose_name='Forma de generar el descuento'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discountType',
            field=models.CharField(choices=[('productPercent', 'Porcentaje del producto'), ('productValue', 'Valor fijo del producto')], default='productValue', max_length=250, verbose_name='Forma de aplicar el descuento'),
        ),
    ]
