# Generated by Django 2.0.5 on 2019-04-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0047_auto_20190415_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='tags',
            new_name='ticketTypes',
        ),
    ]
