# Generated by Django 2.0.5 on 2019-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0048_auto_20190415_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='haveExpenses',
            field=models.BooleanField(default=True, help_text='Crea gastos esta sucursal?', verbose_name='Crea Gastos?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='conditionValue',
            field=models.FloatField(default=1, verbose_name='Valor del descuento'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discountType',
            field=models.CharField(choices=[('productPercent', 'Porcentaje del producto'), ('productValue', 'Valor fijo del producto'), ('totalPercent', 'Descuento del total del ticket')], default='productValue', max_length=250, verbose_name='Forma de aplicar el descuento'),
        ),
    ]
