# Generated by Django 2.0.5 on 2019-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0049_auto_20190423_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketType',
            field=models.CharField(choices=[('VENTA', 'VENTA'), ('REMISION', 'REMISION'), ('DEVOLUCION', 'DEVOLUCION'), ('GASTO', 'GASTO')], default='VENTA', max_length=100),
        ),
    ]
