# Generated by Django 2.0.5 on 2019-04-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0051_ticketproducts_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, help_text='(sugerido)', max_length=250, null=True, verbose_name='Código de Barras '),
        ),
        migrations.AddField(
            model_name='product',
            name='ieps',
            field=models.BooleanField(default=True, help_text='Graba IEPS? (sugerido)', verbose_name='IEPS. '),
        ),
        migrations.AddField(
            model_name='product',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='Este producto tiene precio variable? (sugerido)', verbose_name='Precio dinámico '),
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Se muestra siempre este producto? (sugerido)', verbose_name='Es favorito? '),
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.BooleanField(default=True, help_text='Graba IVA? (sugerido)', verbose_name='I.V.A. '),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, help_text='Graba IVA? (sugerido)', verbose_name='Precio en esta sucursal '),
        ),
        migrations.AlterField(
            model_name='ticketproducts',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SV.Ticket'),
        ),
    ]
