# Generated by Django 2.0.5 on 2019-05-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0052_auto_20190428_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='barcode',
            field=models.BooleanField(default=False, help_text='Activalo para conectar un escaner a una PC', verbose_name='Muestra Escaner?'),
        ),
    ]
