# Generated by Django 2.0.5 on 2019-05-13 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SV', '0053_sellpoint_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='_sellpoint_supervisors_+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisores'),
        ),
    ]
