# Generated by Django 2.0.5 on 2019-05-16 15:21

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0054_sellpoint_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Elige otro menú solo si este menú depende de otro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='SV.Menu', verbose_name='Depende de?'),
        ),
    ]
