# Generated by Django 2.0.5 on 2019-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0055_auto_20190516_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ManyToManyField(help_text='Elige el o los menus donde se vende este producto', related_name='_product_menu_+', to='SV.Menu', verbose_name='Menus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellpoints',
            field=models.ManyToManyField(help_text='Se vende en estas sucursales', related_name='_product_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta'),
        ),
    ]
