# Generated by Django 2.0.5 on 2019-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0056_auto_20190516_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código de Barras '),
        ),
        migrations.AlterField(
            model_name='product',
            name='ieps',
            field=models.BooleanField(default=False, help_text='Este producto graba IEPS? (sugerido)', verbose_name='IEPS. '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='El precio es dinámico? (sugerido)', verbose_name='Precio dinámico '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Este producto es favorito? (sugerido)', verbose_name='Es favorito? '),
        ),
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.BooleanField(default=True, help_text='Este producto graba IVA? (sugerido)', verbose_name='I.V.A. '),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, help_text='Precio para todas las sucursales (sugerido)', verbose_name='Precio en esta sucursal '),
        ),
    ]
