# Generated by Django 2.0.5 on 2019-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0058_sellpoint_have_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellpoint',
            name='have_credit',
        ),
    ]
