# Generated by Django 2.0.5 on 2019-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0059_remove_sellpoint_have_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='have_credit',
            field=models.BooleanField(default=False, help_text='Tiene credito', verbose_name='Tiene credito?'),
        ),
    ]
