# Generated by Django 2.0.5 on 2019-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0061_sellpoint_have_credit_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='have_disscounts',
            field=models.BooleanField(default=False, help_text='Tiene credito', verbose_name='Tiene credito?'),
        ),
    ]
