# Generated by Django 2.0.5 on 2019-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0063_sellpoint_have_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='have_orders',
            field=models.BooleanField(default=False, help_text='Tiene credito', verbose_name='Tiene credito?'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Numero de tickets que imprime'),
        ),
    ]
