# Generated by Django 2.0.5 on 2019-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0065_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Ticket', 'Ve tickets'), ('Can_Update__Ticket', 'Modifica tickets')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Muy breve descripción del producto.', max_length=250, null=True, verbose_name='Atributo o descripción'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('COBRADO', 'COBRADO'), ('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=50),
        ),
    ]
