# Generated by Django 2.0.5 on 2019-06-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0066_auto_20190528_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut',
            options={'default_permissions': [], 'ordering': ['-id'], 'permissions': [('Can_View__Cut', 'Ve cortes'), ('Can_Change__Cuts', 'Modifica cortes')], 'verbose_name': 'Corte', 'verbose_name_plural': 'Cortes'},
        ),
    ]
