# Generated by Django 2.0.5 on 2019-06-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0004_auto_20190611_1356'),
        ('SV', '0067_auto_20190607_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='fiscalDataCuts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='INV.FiscalMX'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='fiscalDataTickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='INV.FiscalMX'),
        ),
    ]
