# Generated by Django 2.0.5 on 2019-07-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0068_auto_20190611_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creditPayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellpoint',
            name='fiscalDataCuts',
            field=models.ForeignKey(blank=True, help_text='Debes darlo de alta en la pestaña de Mi Factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='INV.FiscalMX', verbose_name='RFC que factura Cortes'),
        ),
        migrations.AlterField(
            model_name='sellpoint',
            name='fiscalDataTickets',
            field=models.ForeignKey(blank=True, help_text='Debes darlo de alta en la pestaña de Mi Factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='INV.FiscalMX', verbose_name='RFC que factura Tickets'),
        ),
    ]
