# Generated by Django 2.0.5 on 2019-07-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0071_auto_20190711_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
    ]
