# Generated by Django 2.0.5 on 2019-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0072_remove_product_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketproducts',
            name='id_bckp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
