# Generated by Django 2.0.5 on 2019-08-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0074_sellpoint_haveexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellpoint',
            name='haveExchange',
        ),
    ]
