# Generated by Django 2.0.5 on 2019-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0075_remove_sellpoint_haveexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='haveExchange',
            field=models.BooleanField(default=False, help_text='Entrega cámbio?', verbose_name='Entrega cambio'),
        ),
    ]
