# Generated by Django 2.0.5 on 2019-08-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0076_sellpoint_haveexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Se vende en estas sucursales', null=True, related_name='_product_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta'),
        ),
    ]
