# Generated by Django 2.0.5 on 2019-09-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0034_auto_20190709_1256'),
        ('SV', '0077_auto_20190824_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellpointGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del grupo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mirari.Organization')),
                ('sellpoints', models.ManyToManyField(blank=True, related_name='_sellpointgroups_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta')),
            ],
            options={
                'abstract': False,
                'default_permissions': [],
                'verbose_name': 'Grupo puntos de venta',
                'verbose_name_plural': 'Grupos de puntos de venta',
                'ordering': ['-id'],
                'permissions': [('Can_View__SellpointGroups', 'Ve grupos de puntos de venta'), ('Can_Create__SellpointGroups', 'Crea grupos de puntos de venta'), ('Can_Update__SellpointGroups', 'Modifica grupos de puntos de venta'), ('Can_Delete__SellpointGroups', 'Elimina grupos de puntos de venta')],
            },
        ),
    ]
