# Generated by Django 2.0.5 on 2019-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SV', '0078_sellpointgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpointgroups',
            name='footer1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pie1'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='footer2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pie2'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 1'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 2'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 3'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 4'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 5'),
        ),
        migrations.AddField(
            model_name='sellpointgroups',
            name='line6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Linea 6'),
        ),
    ]
