# Generated by Django 2.0.5 on 2020-02-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirari', '0034_auto_20190709_1256'),
        ('SV', '0079_auto_20190930_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpoint',
            name='bocadillos',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios Bocadillos'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='bocadillosid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MENU'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='cenas',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios Cenas'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='cenasid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MENU'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='comida',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios Comida'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='comidaid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MENU'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='horneado',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios Carne'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='horneadoid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MENU'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='pan',
            field=models.ForeignKey(blank=True, help_text='Asocia una serie a este punto de venta. <strong> Déjalo vacio para asignar folios aleatorios </strong>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mirari.Serial', verbose_name='Serie de folios Pan'),
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='panid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MENU'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='barcode2',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='ticket',
            name='difference',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketType2',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('CENAS', 'CENAS'), ('COMIDA', 'COMIDA'), ('BOCADILLOS', 'BOCADILLOS'), ('PAN', 'PAN'), ('HORNEADO', 'HORNEADO')], default='GENERAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellpoints',
            field=models.ManyToManyField(blank=True, help_text='Se vende en estas sucursales', related_name='_product_sellpoints_+', to='SV.Sellpoint', verbose_name='Puntos de venta'),
        ),
    ]
